### ISSUE TITLE
Validator Stopped Error `Fatal: _getSeedNodes seed list was not signed by archiver`

### ISSUE THREAD

**Issue by 0xtradeall** [Shardeum/shardeum-bug-reporting#237]
##### What is the issue?

I have an issue when running the node:
Fatal: _getSeedNodes seed list was not signed by archiver
    
#### What impact does the issue have?

Trecirculenode stops running

##### What other resources can you share regarding this issue?

state: stopped
exitMessage: 'Fatal: _getSeedNodes seed list was not signed by archiver!'
exitStatus: Exit with error

**Comment by rafalbujak** [comment]
I see after update this same error: 
Node exited with following message: **Fatal: _getSeedNodes seed list was not signed by archiver!**
Validator running version: 1.1.5

**Comment by xxy96** [comment]
update to 1.1.5 also encountered the same, this is the log
[exit.log](https://github.com/Shardeum/shardeum-bug-reporting/files/11065449/exit.log)

**Comment by CzeryGamer** [comment]
and noone help ?

**Comment by MarcusWentz** [comment]
@CzeryGamer 

The core team is looking into this issue.

**Comment by zdzieblowski** [comment]
I'm getting the ``Node exited with following message: Fatal: _getSeedNodes seed list was not signed by archiver!`` in WebUI, but it goes back automatically to StandBy mode ...

```
state: standby
exitMessage: 'Fatal: _getSeedNodes seed list was not signed by archiver!'
exitStatus: Exit with error
totalTimeRunning: 1.66
totalTimeValidating: 0
lastActive: ''
lastRotationIndex: ''
stakeRequirement: '10.0'
nominatorAddress: '0x86c9f7ed7761bd7fda4da473d9b3653164d95814'
nomineeAddress: 7cb73944b23027a188efbfedbd3379d03200ec5bcbeee73d6b2be50a2a66ad59
performance:
  memPercentage: 47.45340849337645
  diskPercentage: 32.35719525997912
  cpuPercentage: 26.60098522167488
currentRewards: '0.0'
lockedStake: '25.4'
nodeInfo: ''
```

**Comment by MarcusWentz** [comment]
What do you see with 
```shell
echo $EXISTSING_ARCHIVERS
```
?

**Comment by zdzieblowski** [comment]
> What do you see with
> 
> ```shell
> echo $EXISTSING_ARCHIVERS
> ```
> 
> ?

Nothing

**Comment by zdzieblowski** [comment]
PS. but I'm on Debian 11 now (previously Ubuntu 20.04 LTS) and have a semi working setup - yesterday it was validating for about 2 hours

current status below:

```
state: standby
totalTimeRunning: 73904.235
totalTimeValidating: '00:00:00'
lastActive: Tue Mar 28 2023 17:39:07 GMT+0000 (Coordinated Universal Time)
lastRotationIndex: 456/463
stakeRequirement: '10.0'
nominatorAddress: '0x86c9f7ed7761bd7fda4da473d9b3653164d95814'
nomineeAddress: 7df8361d30f2d112f671fd7f335c82d9ddbb2f722e5f07f0630345add75e71da
performance:
  memPercentage: 42.65755041214231
  diskPercentage: 17.91780289365244
  cpuPercentage: 1.5000000000000013
currentRewards: '2.166666666666666666'
lockedStake: '20.0'
nodeInfo:
  id: 169e53d0b37ff02780f686851081a8ba392f2994ba2a9771f927064b755a3a64
  publicKey: 7df8361d30f2d112f671fd7f335c82d9ddbb2f722e5f07f0630345add75e71da
  curvePublicKey: 2b2d8108b79bc6245b96b8293f7f5765357d2a4207ba3cb3ab2de7901dc69277
  externalIp: ---
  externalPort: 9001
  internalIp: ---
  internalPort: 10001
  status: standby
```
