### ISSUE TITLE
Validator Version 1.1.6 status `Null` Earning SHM rewards stopped

### ISSUE THREAD

**Issue by DuongPAD** [Shardeum/shardeum-bug-reporting#292]
##### What is the issue?

:red_circle:  My Validator nodes are giving status null error. :red_circle: 
    
#### What impact does the issue have?

:red_circle: My validator nodes are getting status: null, totalTimeValidating is still growing, but currentRewards hasn't changed all the time.. :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
state: null
totalTimeRunning: 121365.881
totalTimeValidating: 1 Days 9 Hours 40 Minutes
lastActive: Mon Apr 03 2023 03:53:07 GMT+0000 (Coordinated Universal Time)
lastRotationIndex: 340/343
stakeRequirement: '10.0'
nominatorAddress: '0x9035daba15e48d8796285666d0abbdd7db6*****'
nomineeAddress: 87099503fa49571318631095b8fb47964b33cc31a9989c113e958717979*****
performance:
  memPercentage: 29.498259616639842
  diskPercentage: 24.271524091210637
  cpuPercentage: 4.1015625
currentRewards: '2.1'
lockedStake: '60.0'
nodeInfo:
  id: 66725422a081f28d3f12aada4031019f61363010a008a687ccf2812f8dc*****
  publicKey: 87099503fa49571318631095b8fb47964b33cc31a9989c113e958717979*****
  curvePublicKey: ******
  externalIp: 38.242.228.86
  externalPort: 9001
  internalIp: 38.242.228.86
  internalPort: 10001
  status: null

```
:red_circle:
