### ISSUE TITLE
Validator Stopped Error ```Cannot read properties of undefined (reading 'certExp')```

### ISSUE THREAD

**Issue by whiskas27** [Shardeum/shardeum-bug-reporting#65]
After about 24 hours of node runnig got this error
It hasn't baceme in the active set,restarted successfully 
<img width="486" alt="2023-02-16_23 00 34" src="https://user-images.githubusercontent.com/25068101/219489950-246fe222-8746-4df1-92cb-f0ac4d1984a9.png">
Discord - Bodbka#7596
Wallet used to run validator and delegate to myself - 0x2417Eb432DD355bA6F3B6699f620DEC86D5Cea60

**Comment by bombermine3** [comment]
Same here.

##### What is the issue?

From time to time the node crashes with an error:
```
state: stopped                                                                                                                                                                
exitMessage: Cannot read properties of undefined (reading 'certExp')                                                                                                          
exitStatus: Exit with error                                                                                                                                                   
performance:                                                                                                                                                                  
  memPercentage: 93.12698116538164                                                                                                                                            
  diskPercentage: 8.392694675291635                                                                                                                                           
  cpuPercentage: 2.0050125313283207                                                                                                                                           
stakeRequirement: '10.0'                                                                                                                                                      
lockedStake: '12.0'                                                                                                                                                           
nominatorAddress: '0x700a023f22c4a4fbfdeed3d00b951ef8ea932be1'                                                                                                              
```
    
#### What impact does the issue have?

Node stops completely. A manual restart is required

##### How to reproduce the issue? 

 I just installed the node according to the official guide

##### What other resources can you share regarding this issue?
