### ISSUE TITLE
submitStandbyRefresh: Error posting standbyRefresh request

### ISSUE THREAD

**Issue by stefanorg** [Shardeum/shardeum-bug-reporting#652]
##### What is the issue?

node exited with following error: `submitStandbyRefresh: Error posting standbyRefresh request`

```
node@f932b285910c:~/app$ operator-cli status
state: stopped
exitMessage: >-
  submitStandbyRefresh: Error posting standbyRefresh request: RequestError:
  connect ECONNREFUSED 185.202.239.12:9034
exitStatus: Exit with error
performance:
  memPercentage: 9.003195034739349
  diskPercentage: 15.438341447295192
  cpuPercentage: 1.3355592654423987
stakeRequirement: '10.0'
lockedStake: '10.0'
nominatorAddress: '0x86d4fb816b4aa76f8ee6ab5eee865cc3e188e070'
currentRewards: '53.599999999999999999'
autorestart: true
```
    
#### What impact does the issue have?

the node was stopped

##### How to reproduce the issue? 

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
    -where the error is seen
    -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
    -share code and explain how the code was run
```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle:
