### ISSUE TITLE
Validator Stopped With Error ```removed from network in normal conditions```

### ISSUE THREAD

**Issue by PsyWirZ0ut31** [Shardeum/shardeum-bug-reporting#72]
##### What is the issue?
![image](https://user-images.githubusercontent.com/125697731/219781876-2e2564af-061b-4960-b7e2-c540124178c6.png)
node stop with no reason 
Describe the error in simple terms
    
#### What impact does the issue have?
need to relaunch my node so very bad ... i want to launch it one time and it's good after but no..
Describe if the bug is a visual warning or if it breaks functionality causing a system to fail
tell me "remove node for network in normal conditions"
##### How to reproduce the issue? 
i don't know
Explain in as much detail as possible to help reproduce the bug:
    -where the error is seen
    -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
    -share code and explain how the code was run

##### What other resources can you share regarding this issue?

Photos and links related to the error.
![image](https://user-images.githubusercontent.com/125697731/219781876-2e2564af-061b-4960-b7e2-c540124178c6.png)

**Comment by YungMoses** [comment]
same happened to me twice. Both times my validator has been active for some time and gaining rewards then it will suddenly stop and show the same message as above. I hope my progress as a validator is saved.

**Comment by bombermine3** [comment]
I have the same
```
state: stopped                                                                                                                                                                
exitMessage: removed from network in normal conditions                                                                                                                        
exitStatus: Exited cleanly                                                                                                                                                    
performance:                                                                                                                                                                  
  memPercentage: 88.05097331389405                                                                                                                                            
  diskPercentage: 8.551623458500087                                                                                                                                           
  cpuPercentage: 1.7456359102244412                                                                                                                                           
stakeRequirement: '10.0'                                                                                                                                                      
lockedStake: '12.0'                                                                                                                                                           
nominatorAddress: '0x700a023f22c4a4fbfdeed3d00b951ef8ea932be1'
```
