### ISSUE TITLE
invoke-exit: node left active state due to un-refuted lost report

### ISSUE THREAD

**Issue by stefanorg** [Shardeum/shardeum-bug-reporting#721]
##### What is the issue?

:red_circle:  Describe the error in simple terms. :red_circle: 

Validator stopped
    
node detail:

```node@a8900faefa46:~/app$ operator-cli status
state: stopped
exitMessage: >-
  invoke-exit: node left active state due to un-refuted lost report
  exitUncleanly
exitStatus: Exit with error
performance:
  memPercentage: 9.186859510706313
  diskPercentage: 16.254238319912563
  cpuPercentage: 1.340033500837523
stakeRequirement: '10.0'
lockedStake: '10.0'
nominatorAddress: '0x86d4fb816b4aa76f8ee6ab5eee865cc3e188e070'
currentRewards: '112.624951388888888887'
autorestart: true

```

```

$ operator-cli version
runningCliVersion: 1.2.1
runningCliBranch: main
minimumCliVersion: 0.1.0
latestCliVersion: 1.2.1
minShardeumVersion: 1.10.3
activeShardeumVersion: 1.10.3
runningGuiVersion: 1.2.0
runningGuiBranch: main
minimumGuiVersion: 0.1.0
latestGuiVersion: 1.2.0
runnningValidatorVersion: 1.10.3
runningValidatorBranch: beta1.10.3hotfix-rc4
```

**Comment by stefanorg** [comment]
and again same error 

```
node@a8900faefa46:~/app$ operator-cli status
state: stopped
exitMessage: >-
  invoke-exit: node left active state due to un-refuted lost report
  exitUncleanly
exitStatus: Exit with error
performance:
  memPercentage: 9.264234301896863
  diskPercentage: 16.522358363021507
  cpuPercentage: 3.1561461794019974
stakeRequirement: '10.0'
lockedStake: '10.0'
nominatorAddress: '0x86d4fb816b4aa76f8ee6ab5eee865cc3e188e070'
currentRewards: '123.546137499999999998'
autorestart: true

```
